<?php

use Drupal\Core\Config\FileStorage;
use Drupal\field\Entity\FieldConfig;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\node\Entity\Node;

/**
 * Be sure the fields we're expecting are there, and create if not.
 *
 * ASSUMPTIONS:
 * - You've already created these field configs, probably through the GUI.
 * - They're stored in ../config.
 *
 * @param array $entitytypes_fields
 *   A 3-dimensional array. The first level is entity types, the second is
 * bundles, and the third is the fields you want to ensure. E.g.
 * [
 *   'node' => [
 *     'page' => [
 *       'field_foo',
 *       'field_bar',
 *     ],
 *     'article' => [
 *       'field_bar',
 *     ],
 *   ],
 * ]
 *
 * @throws \Drupal\Core\Entity\EntityStorageException
 */
function _ensure_fields(array $entitytypes_fields) {
  $config_directory = new FileStorage('config');
//dsm($entitytypes_fields);
  foreach ($entitytypes_fields as $entitytype => $bundles) {
    foreach ($bundles as $bundle => $fields) {
      foreach ($fields as $field) {
        $field_storage_name = 'field.storage.' . $entitytype . '.' . $field;
        $config_record = $config_directory->read($field_storage_name);
        if (!FieldStorageConfig::loadByName($config_record['entity_type'], $config_record['field_name'])) {
          FieldStorageConfig::create($config_record)->save();
        }

        $field_config_name = 'field.field.' . $entitytype . '.' . $bundle . '.' . $field;
        $config_record = $config_directory->read($field_config_name);
        if (!FieldConfig::loadByName($config_record['entity_type'], $config_record['bundle'], $config_record['field_name'])) {
          FieldConfig::create($config_record)->save();
        }
      }
  /**
 * Adds "External ID" field to articles and "Second image" to two-col CTAs.
 */
function test_update_8101(&$sandbox) {
  $entitytypes_fields = [
    'node' => [
      'page' => [
        'field_external_id',
      ],
      'blog_news_post' => [
        'field_external_id',
      ],
    ],
    'paragraph' => [
      'two_column_cta' => [
        'field_second_image',
      ],
    ],
  ];

  _ensure_fields($entitytypes_fields);
}
    }
  }
}
