<?php


use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\user\Entity\User;
/**
 * Implements hook_entity_base_field_info().
 */
function my_custom_fields_entity_base_field_info(EntityTypeInterface $entity_type) {
    
 if ($entity_type->id() === 'node') {
    // dsm($entity_type->id());
//  $fields['my_custom_field'] = BaseFieldDefinition::create('my_custom_field')
//  ->setLabel(t('The custom field'))
//  ->setDisplayConfigurable('form', TRUE)
//  ->setDisplayConfigurable('view', TRUE);
//  return $fields;
 }
}