<?php

/**
 * @file
 * Contains migrate_discography.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function migrate_discography_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the migrate_discography module.
    case 'help.page.migrate_discography':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migrate example with a discography content model.') . '</p>';
      return $output;

    default:
  }
}
