_core:
  default_config_hash: EX0ic0iEdUTHNFbLC3SHAAMaGQBiCySQnsa9DTV8HGo
output_values:
  title: title
  absolute: absolute
  options: options
  key: 0
  description: 0
  uri: 0
  alias: 0
  external: 0
  relative: 0
  existing: 0
  weight: 0
  expanded: 0
  enabled: 0
  uuid: 0
add_fragment: 1
base_url: ''
