# Schema for the configuration files of the MyCustomFields module.
# field.value.my_custom_field:
#  type: mapping
#  label: 'Default value'
#  mapping:
#  value:
#  type: string
#  label: 'MyCustomFields'